### ISSUE TITLE
Implementacja mechanizmu odczytu plików XML.

### ISSUE THREAD

**Issue by AOlbromski** [AOlbromski/SPDev#2]
Implementacja mechanizmu odwzorowującego informacje zawarte w plikach XML na obiekty modelu.

**Comment by alapierre** [comment]
proponuję użyć JAXB - wbudowany w JAVA mechanizm serializacji / deserializacji obiektów do postaci XML. Wydajny i wygodny. Można użyć naszego utila: utils-xml

**Comment by AOlbromski** [comment]
Implementacja zakończona.
